# SPDX-License-Identifier: MIT
"""Local first-observation trial and exact user-supplied044 restore package.

Never writes an SD drive or installs firmware. Binaries remain outside Git.
"""
from pathlib import Path
import argparse,hashlib,json,zipfile
from nes_report084_prepare import sha,ROOT
FW='b2895696ab5c665b2b9a0a4acf3997f0ca13442b40e6f1ebf4abc3513036db1e'
RESTORE='1c3b40a3459d24114cb4d91ee9d861d1a08025a670ef25317ef489092203693b'
OFFLINE='b1f089f563727faca3b2327e0fd3c85f4d70126c3eeced18f6761bb54ff17708'
def digest(b):return hashlib.sha256(b).hexdigest()
def make_zip(path,files):
 with zipfile.ZipFile(path,'x',zipfile.ZIP_DEFLATED) as z:
  for n,b in sorted(files.items()):
   assert not n.startswith('/') and '..' not in Path(n).parts
   item=zipfile.ZipInfo(n,(2026,10,8,0,0,0));item.compress_type=zipfile.ZIP_DEFLATED;z.writestr(item,b)
 with zipfile.ZipFile(path) as z:
  assert set(z.namelist())==set(files) and z.testzip() is None
  for n,b in files.items():assert z.read(n)==b,n
 return {'bytes':path.stat().st_size,'sha256':sha(path),'members':{n:digest(b) for n,b in files.items()}}
def main():
 p=argparse.ArgumentParser()
 for n in ['arm','evidence075','host','out']:p.add_argument('--'+n,type=Path,required=True)
 a=p.parse_args();out=a.out.resolve();assert not out.exists();out.mkdir(parents=True)
 s=a.arm/'source';fw=s/'src/obj-report079/firmware.stm';assert fw.stat().st_size==132880 and sha(fw)==FW
 arm=json.loads((a.arm/'arm-check084.json').read_bytes());assert arm['firmware_sha256']==FW
 assert sha(s/'src/nes_report_platform084.c')==sha(ROOT/'src/nes/firmware/nes_report_platform084.c')
 assert sha(s/'src/nes_report_platform084.c')==sha(a.host/'nes_report_platform084.c')
 for n in ['nes_report_space084.c','nes_report_layout084.h','nes_report_boot080.c','nes_report_checkpoint079.c']:
  assert sha(s/'src'/n)==sha(a.host/n),n
 assert 'PASS084 checks=809' in (a.host/'run.log').read_text()
 assert 'PASS083 TIMER checks=5' in (a.host/'timer.log').read_text()
 host=json.loads((a.host/'result.json').read_bytes())
 for n,h in host['files'].items():assert sha(a.host/n)==h,n
 assert sha(a.evidence075/'manifest.json')==OFFLINE
 pins=json.loads((a.evidence075/'manifest.json').read_bytes())['files']
 restore=a.evidence075/'inputs/firmware.stm';assert sha(restore)==RESTORE==pins['inputs/firmware.stm']
 assert restore.stat().st_size==169056
 files={'test/sd2snes/firmware.stm':fw.read_bytes(),'restore/sd2snes/firmware.stm':restore.read_bytes(),
        'README.ko.md':(ROOT/'docs/SDREPORT084-RUN.ko.md').read_bytes(),'LICENSE.txt':(s/'LICENSE').read_bytes()}
 inventory={n:{'bytes':len(b),'sha256':digest(b)} for n,b in files.items()}
 manifest=dict(candidate='SDREPORT084',purpose='first external observation trial, not NES or CF68 release',
               hardware_verified=False,automatic_install=False,restore_role='exact user-supplied last-successful044; not HW002 firmware',files=inventory)
 files['manifest.json']=(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n').encode()
 trial=make_zip(out/'FXPAK-SDREPORT084-TRIAL.zip',files)
 # Include exact prepared sources (including LICENSE and original notices),
 # plus the two generated byte-array headers consumed by this ARM build.
 prep=json.loads((a.arm/'preparation084.json').read_bytes());sources={}
 for n,h in prep['files'].items():
  if n=='src/.ARG_VERSION':
   # Make updates this argument cache from081 to084; it is not C source.
   assert (s/n).read_text()=='"SDREPORT084"',n
  else:assert sha(s/n)==h,n
  assert not any(x in n.lower() for x in ['license.dat','.pem','credentials']),n
  sources['source/'+n]=(s/n).read_bytes()
 for n in ['cfgware.h','autoconf.h']:
  sources['build-inputs/'+n]=(s/'src/obj-report079'/n).read_bytes()
 for n in ['nes_report084_prepare.py','build_nes_report079_arm.ps1','check_nes_report084_arm.py','package_nes_report084.py']:
  sources['tools/'+n]=(ROOT/'tools'/n).read_bytes()
 sources['BUILD-NOTES.txt']=b'SDREPORT084; Cortex-M4 ARM GNU13.3.Rel1; use supplied build_nes_report079_arm.ps1 with source and pinned mini image. Output directory obj-report079 is historical; VERSION is SDREPORT084. Source snapshot contains exact final084 platform and unchanged081 native code. Host tools/ARM toolchain are external dependencies. No hardware execution claimed.\n'
 source=make_zip(out/'FXPAK-SDREPORT084-SOURCE.zip',sources)
 record=dict(candidate='SDREPORT084',trial=trial,source=source,firmware_sha256=FW,restore_sha256=RESTORE,
             full_member_readback=True,hardware_verified=False,installed=False,scope='report-only observation trial')
 (out/'package-check084.json').write_text(json.dumps(record,indent=2)+'\n',encoding='utf-8')
 print(json.dumps({k:record[k] for k in ['candidate','firmware_sha256','restore_sha256','full_member_readback','hardware_verified','installed']}))
if __name__=='__main__':main()
